<p style="color: gray; 
          text-align: center;
          font-size: 24px;">
Inicialização de Bibliotecas</p>

In [1]:
import sys;sys.path.append('src')
import cv2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import time
from src import functions as f
from collections import deque

<p style="color: gray; 
          text-align: center;
          font-size: 24px;">
Ajuste Foco Camera</p>

In [2]:
cap = cv2.VideoCapture(0)

cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0.25)
cap.set(cv2.CAP_PROP_EXPOSURE, -1)

cap.set(cv2.CAP_PROP_AUTOFOCUS, 0)
cap.set(cv2.CAP_PROP_FOCUS, 10)

print("Exposição:", cap.get(cv2.CAP_PROP_EXPOSURE))
print("Foco:", cap.get(cv2.CAP_PROP_FOCUS))


Exposição: -6.0
Foco: -1.0


In [3]:
def positioning(frame,frame2): 
    if np.sum(frame[:160,:160]) > 0:
        cv2.putText(frame2,                      
            'Diag. Esq',           
            (300, 470),                   
            cv2.FONT_HERSHEY_SIMPLEX,   
            1,                         
            (0, 0, 255),                
            2,                          
            cv2.LINE_AA)    
    elif np.sum(frame[:160,480:]):
        cv2.putText(frame2,                      
                'Diag. Dir',           
                (300, 470),                   
                cv2.FONT_HERSHEY_SIMPLEX,   
                1,                         
                (0, 0, 255),                
                2,                          
                cv2.LINE_AA)    
    elif np.sum(frame[:160,160:480]) > 0:
        cv2.putText(frame2,                      
            'Cima',           
            (300, 470),                   
            cv2.FONT_HERSHEY_SIMPLEX,   
            1,                         
            (0, 0, 255),                
            2,                          
            cv2.LINE_AA)   
    elif np.sum(frame[160:320,:160]) > 0:
        cv2.putText(frame2,                      
                'Esquerda',           
                (300, 470),                   
                cv2.FONT_HERSHEY_SIMPLEX,   
                1,                         
                (0, 0, 255),                
                2,                          
                cv2.LINE_AA)    
    elif np.sum(frame[160:320,480:]) > 0:
        cv2.putText(frame2,                      
                'Direita',           
                (300, 470),                   
                cv2.FONT_HERSHEY_SIMPLEX,   
                1,                         
                (0, 0, 255),                
                2,                          
                cv2.LINE_AA)


In [7]:
cap = cv2.VideoCapture(0)
tensor = deque(maxlen=10)
division = 32

while True:
    ret,frame_original = cap.read()
    frame_original = f.mirroring(frame_original)
    frame = frame_original.copy()
    frame = f.gray_scale(frame)
    frame = f.background_subtraction(cam_frame=frame,start_time=5,limiar=15)
    frame,vec = f.down_sampling(frame,division=division)
    frame = f.binarization(frame,limiar=5)
    vec = f.binarization(vec,limiar=5)
    original_view = frame_original.copy()
    original_view,vec_positioning = f.bounding_box(frame,original_view,division=division)
    positioning(frame,original_view)
    
    tensor.append(frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
    elif cv2.waitKey(1) & 0xFF == ord('1'):
        f.background_subtraction.background = f.gray_scale(frame_original.copy())
        frame_original = np.full_like(frame_original,255)

    elif cv2.waitKey(1) & 0xFF == ord('2'):
        tensor = np.array(tensor)
        np.save(r'readme_media\tensor.npy', tensor)
        break

    if not ret:
        break
    print(vec_positioning)

    cv2.imshow('Original',original_view)
    cv2.imshow('Visualizer',frame)
    cv2.imshow('vec',vec)


cap.release()
cv2.destroyAllWindows()

(np.int64(0), np.int64(17), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(0), np.int64(19), np.int64(5), np.int64(14))
(np.int64(

In [5]:
while True:
    cam = cv2.VideoCapture('readme_media\wave.gif')
    while True:
        ret,frame = cam.read()
        
        if cv2.waitKey(125) & 0xFF == ord('q'):
            break
        if not ret:
            break
        frame_vizualizer = frame.copy()
        frame = f.gray_scale(frame)
        x,y = np.where(frame == 255)
        x_min,x_max = np.min(x),np.max(x)
        y_min,y_max = np.min(y),np.max(y)

        frame_vizualizer[x_min:x_max,y_min] = [255,0,255]
        frame_vizualizer[x_min:x_max,y_max] = [255,0,255]
        frame_vizualizer[x_min,y_min:y_max] = [255,0,255]
        frame_vizualizer[x_max,y_min:y_max] = [255,0,255]
        print(y)
        cv2.imshow('Vid',frame_vizualizer)
    if cv2.waitKey(500) & 0xFF == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()

<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Vinic\AppData\Local\Temp\ipykernel_36156\1857388891.py:2: SyntaxWarning: invalid escape sequence '\w'
  cam = cv2.VideoCapture('readme_media\wave.gif')


[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
[288 289 290 ... 381 382 383]
